# Generated by Django 4.1.1 on 2022-09-12 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('state', models.TextField(blank=True, null=True)),
                ('warehouse_image', models.ImageField(blank=True, default='media/warehouse/no_image.png', null=True, upload_to='media/warehouse/')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_owner_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
    ]
