# Generated by Django 4.1.1 on 2022-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_chargesperwarehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'KILOGRAM'), ('lbs', 'POUND'), ('oz', 'Ounce')], default='kg', max_length=3),
        ),
    ]
