# Generated by Django 4.1.1 on 2022-09-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_quantity_product_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='products/no_image.png', null=True, upload_to='products/'),
        ),
    ]
